-- Table: {schema}.item

-- DROP TABLE IF EXISTS {schema}.item;

CREATE TABLE IF NOT EXISTS {schema}.item
(
    item_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title text COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp with time zone DEFAULT now(),
    updated_date timestamp with time zone DEFAULT now(),
    item_state_id integer NOT NULL,
    created_by uuid NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    assigned_to uuid NULL,
    priority_id integer not null DEFAULT 0,
    CONSTRAINT item_pkey PRIMARY KEY (item_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS {schema}.item
    OWNER to postgres;

COMMENT ON TABLE {schema}.item
    IS 'the backlog';