-- Table: {schema}.item

-- DROP TABLE IF EXISTS {schema}.item;

CREATE TABLE IF NOT EXISTS {schema}.item
(
    item_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title text COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default" NOT NULL,
    org_id uuid not null,
    created_date timestamp with time zone DEFAULT now(),
    updated_date timestamp with time zone DEFAULT now(),
    item_state_id integer NOT NULL,
    created_by uuid DEFAULT '00000000-0000-0000-0000-000000000000'::uuid,
    assigned_to uuid,
    priority_id integer NOT NULL DEFAULT 0,
    rank integer not null DEFAULT 0,
    search_vector tsvector GENERATED ALWAYS AS (
        setweight(to_tsvector('english'::regconfig, COALESCE(title, ''::text)), 'A'::"char") || 
        setweight(to_tsvector('english'::regconfig, COALESCE(body, ''::text)), 'B'::"char")
    ) STORED,
    CONSTRAINT item_pkey PRIMARY KEY (item_id),
    CONSTRAINT fk_{schema}_item_assigned_to FOREIGN KEY (assigned_to)
        REFERENCES {schema}."user" (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_{schema}_item_created_by FOREIGN KEY (created_by)
        REFERENCES {schema}."user" (user_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_{schema}_item_priority_id FOREIGN KEY (priority_id)
        REFERENCES {schema}.priority (priority_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_{schema}_item_org_id FOREIGN KEY (org_id)
        REFERENCES {schema}.organization (org_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION,
    CONSTRAINT fk_{schema}_item_item_state_id FOREIGN KEY (org_id, item_state_id)
        REFERENCES {schema}.item_state (org_id, item_state_id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS {schema}.item
    OWNER to postgres;

COMMENT ON TABLE {schema}.item
    IS 'the backlog';

-- Index: full_text_search_{schema}_item
DROP INDEX IF EXISTS {schema}.full_text_search_{schema}_item;
CREATE INDEX IF NOT EXISTS full_text_search_{schema}_item
    ON {schema}.item USING gin
    (search_vector)
    TABLESPACE pg_default;

-- Index: idx_{schema}_item_assigned_to
DROP INDEX IF EXISTS {schema}.idx_{schema}_item_assigned_to;
CREATE INDEX IF NOT EXISTS idx_{schema}_item_assigned_to
    ON {schema}.item USING btree
    (assigned_to ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: idx_{schema}_item_created_by
DROP INDEX IF EXISTS {schema}.idx_{schema}_item_created_by;
CREATE INDEX IF NOT EXISTS idx_{schema}_item_created_by
    ON {schema}.item USING btree
    (created_by ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: idx_{schema}_item_created_date
DROP INDEX IF EXISTS {schema}.idx_{schema}_item_created_date;
CREATE INDEX IF NOT EXISTS idx_{schema}_item_created_date
    ON {schema}.item USING btree
    (created_date ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: idx_{schema}_item_item_state_id
DROP INDEX IF EXISTS {schema}.idx_{schema}_item_item_state_id;
CREATE INDEX IF NOT EXISTS idx_{schema}_item_item_state_id
    ON {schema}.item USING btree
    (item_state_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: idx_{schema}_item_priority_id
DROP INDEX IF EXISTS {schema}.idx_{schema}_item_priority_id;
CREATE INDEX IF NOT EXISTS idx_{schema}_item_priority_id
    ON {schema}.item USING btree
    (priority_id ASC NULLS LAST)
    TABLESPACE pg_default;

-- Index: idx_{schema}_item_updated_date
DROP INDEX IF EXISTS {schema}.idx_{schema}_item_updated_date;
CREATE INDEX IF NOT EXISTS idx_{schema}_item_updated_date
    ON {schema}.item USING btree
    (updated_date ASC NULLS LAST)
    TABLESPACE pg_default;