-- Table: {schema}.item

DROP TABLE IF EXISTS {schema}.item;

CREATE TABLE IF NOT EXISTS {schema}.item
(
    item_id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    title text COLLATE pg_catalog."default" NOT NULL,
    body text COLLATE pg_catalog."default" NOT NULL,
    created_date timestamp with time zone DEFAULT now(),
    updated_date timestamp with time zone DEFAULT now(),
    item_state_id integer NOT NULL,
    created_by uuid NULL DEFAULT '00000000-0000-0000-0000-000000000000',
    assigned_to uuid NULL,
    priority_id integer not null DEFAULT 0,
    CONSTRAINT item_pkey PRIMARY KEY (item_id)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS {schema}.item
    OWNER to postgres;

COMMENT ON TABLE {schema}.item
    IS 'the backlog';

-- Indexes
CREATE INDEX idx_{schema}_item_created_date ON {schema}.item(created_date);
CREATE INDEX idx_{schema}_item_updated_date ON {schema}.item(updated_date);
CREATE INDEX idx_{schema}_item_item_state_id ON {schema}.item(item_state_id);

-- FK indexes
CREATE INDEX idx_{schema}_item_priority_id ON {schema}.item(priority_id);
CREATE INDEX idx_{schema}_item_assigned_to  ON {schema}.item(assigned_to);
CREATE INDEX idx_{schema}_item_created_by   ON {schema}.item(created_by);

-- FKs
ALTER TABLE {schema}.item 
ADD CONSTRAINT fk_{schema}_item_priority_id
FOREIGN KEY (priority_id) REFERENCES {schema}.priority(priority_id);

ALTER TABLE {schema}.item 
ADD CONSTRAINT fk_{schema}_item_assigned_to
FOREIGN KEY (assigned_to) REFERENCES {schema}.user(user_id);

ALTER TABLE {schema}.item 
ADD CONSTRAINT fk_{schema}_item_created_by
FOREIGN KEY (created_by) REFERENCES {schema}.user(user_id);

-- Full Text Search

-- Add a computed tsvector column with weighted fields
ALTER TABLE {schema}.user 
ADD COLUMN search_vector TSVECTOR
GENERATED ALWAYS AS (
 setweight(to_tsvector('english', COALESCE(title, '')), 'A') ||
 setweight(to_tsvector('english', COALESCE(body, '')), 'B') 
) STORED;

-- Create the inverted index
CREATE INDEX {schema}.full_text_search_item 
ON {schema}.user 
USING GIN(search_vector);