<#
    .SYNOPSIS
       Create an Item-Organization 
       for the Specified Connection String and Schema
       With Optional Role

    .OUTPUTS
        Postgres Objects
        Sucess or failure 
#>

Param (
    # Connection String for Postgres
    [string]$ConnectionString = "postgresql://postgres:password123-@localhost:5432/postgres",
    # Schema name to create queue in
    [string]$SchemaName = "myio",
    # (optional) Role Name
    [string]$RoleName = ''
)

Import-Module Microsoft.PowerShell.Utility

# Constantts
[int]$ORDER_INDEX_MIN = 110;

# Variables
[int]$exitCode = 0;
[string]$pbin = 'C:\Program Files\PostgreSQL\16\bin\psql.exe';

#
# Functions

<#
    Generated by Gemini
#>
function Find-GitRepositoryRoot {
    param (
        [Parameter(Mandatory = $true)]
        [string]$FilePath
    )

    [string]$herePath = $FilePath
    [bool]$isFile = Test-Path -Path $herePath -PathType Leaf
    # Write-Output "${herePath}: Is Leaf: $isFile"
    if ($isFile) {
        $herePath = (Get-Item $FilePath).DirectoryName
    }
    
    while (($null -ne $herePath) -and ($herePath.Length -gt 0)) {
        [string]$lookFor = Join-Path -Path $herePath -ChildPath ".git"
        # Write-Output "HP: ${herePath}, LF: ${lookFor}"
        if (Test-Path $lookFor -PathType Container) {
            return $herePath
        }
        $herePath = (Get-Item $herePath).Parent.FullName
    }

    Write-Warning "${FilePath}: No Git repository found in the path or its parent directories."
    return $null
}

function Get-OrderIndex {
    param (
        [string]$ScriptName
    )
    [int]$orderIndex = -1;
    [int]$index = $ScriptName.IndexOf('_');
    if ($index -ge 0) {
        [string]$v = $ScriptName.Substring(0, $index);
        [int]$tv = 0;
        if ([int]::TryParse($v, [ref]$tv)) {
            $orderIndex = $tv;
        }
    }
    return $orderIndex;
}

#
# Main
#
Set-StrictMode -Version 2.0
[Net.ServicePointManager]::SecurityProtocol = [Net.SecurityProtocolType]::Tls -bor [Net.SecurityProtocolType]::Tls11 -bor [Net.SecurityProtocolType]::Tls12

if ([string]::IsNullOrWhiteSpace($ConnectionString)) {
    Write-Error "`-ConnectionString` is a required parameter";
    $exitCode = 1;
}

if ([string]::IsNullOrWhiteSpace($SchemaName)) {
    Write-Error "`-SchemaName` is a required parameter";
    $exitCode = 2;
}

if (-not [System.IO.File]::Exists($pbin)) {
    Write-Error "The PG SQL Tools must be installed locally @ ${pbin}"
    $exitCode = 3;
}

$GIT_ROOT = Find-GitRepositoryRoot -FilePath $PSScriptRoot
if ($null -eq $GIT_ROOT) {
    Write-Error "Not in GIT Repo"
    $exitCode = 9;
}

if ($exitCode -gt 0) {
    return $exitCode;
}

Push-Location $GIT_ROOT

# Copy SQL Files to temp
[string]$sqlFolder = Join-Path -Path $GIT_ROOT -ChildPath "data/iodb";
[string]$tempFolder = Join-Path -Path $GIT_ROOT -ChildPath "data/temp";
if (Test-Path $tempFolder) {
    Remove-Item $tempFolder -Force -Recurse 
}
$null = New-Item -Path $tempFolder -ItemType Directory
Copy-Item -Path "$sqlFolder\*.sql" -Destination $tempFolder

# replace schema and role in all files
$SQL_FILES = Get-ChildItem -Path "${tempFolder}\*.sql" -File -Recurse
$SQL_FILES = $SQL_FILES | Sort-Object 
foreach ($FilePath in $SQL_FILES) {
    (Get-Content -Raw -Path $FilePath) -replace "{schema}", "${SchemaName}" | Set-Content -Path $FilePath -NoNewline
    if (-not [string]::IsNullOrWhiteSpace($RoleName)) {
        (Get-Content -Raw -Path $FilePath) -replace "{rolename}", "${RoleName}" | Set-Content -Path $FilePath -NoNewline
    }
}

# Make linux line endings
foreach ($FilePath in $SQL_FILES) {
    (Get-Content -Raw -Path $FilePath) -replace "`r`n", "`n" | Set-Content -Path $FilePath -NoNewline
}

# Play the SQL Scripts (in order) at Postgres Instance
foreach ($FilePath in $SQL_FILES) {
    [string]$filename = [System.IO.Path]::GetFileName($FilePath)
    [int]$oi = Get-OrderIndex -ScriptName $filename;
    if ($oi -ge $ORDER_INDEX_MIN) {
        try {
            Write-Output "`n=============================================="
            Write-Output "Executing: ${filename}"
            Write-Output "=============================================="
            # Set-PSDebug -Trace 2   
            . $pbin -f $FilePath $ConnectionString
        }
        catch {
            Write-Output "Error: $_"
        } 
        finally {
            # Set-PSDebug -Off
        }
    }
}

#
# Exit()
Pop-Location
return $exitCode;